PMS\Bundle\UserBundle\Entity\Organization:
    type: entity
    table: organization
    id:
        type: id
        generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 180